apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: workertemplate-decode-meta
spec:
  workerTemplate:
    metadata:
      labels:
        heimdall.moreh.io/role: decode
