apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: vllm-prefill
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.runtimeBase.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        heimdall.moreh.io/role: prefill # DEPRECATED
        mif.moreh.io/role: prefill
    spec:
      imagePullSecrets:
        - name: moreh-registry
      containers:
        - name: main
          image: 255250787067.dkr.ecr.ap-northeast-2.amazonaws.com/quickstart/moreh-vllm:20250915.1
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          command:
            - /bin/bash
            - -c
          args:
            - |
              set -ex

              if [ -e "$ISVC_PRESET_PATH" ]; then
                eval "$(python3 '
              {{- .Files.Get "files/convert_preset.py.nofmt" | nindent 14 -}}
              ')"
              fi

              # Clear /dev/shm on start to prevent running out of space when crashes occur
              # https://github.com/llm-d/llm-d/issues/352
              find /dev/shm -type f -delete

              cleanup() {
                echo "Received SIGTERM, killing child processes..."
                pkill -P $$
                wait
              }
              trap cleanup SIGTERM SIGINT

              if [ -n "$ISVC_PRE_PROCESS_SCRIPT" ]; then
                echo "Running pre-process script..."
                eval "$ISVC_PRE_PROCESS_SCRIPT"
              fi

              _kv_events_args=()
              if [ "${ISVC_USE_KV_EVENTS:-false}" = "true" ]; then
                _inference_pool_name="{{ "{{" }} if .Spec.InferencePoolRefs {{ "}}" }}{{ "{{" }} (index .Spec.InferencePoolRefs 0).Name {{ "}}" }}{{ "{{" }} end {{ "}}" }}"
                if [ -z "$_inference_pool_name" ]; then
                  echo "Set inferencePoolRefs in InferenceService"
                  exit 1
                fi
                if [ -z "$ISVC_MODEL_NAME" ]; then
                  echo "Set ISVC_MODEL_NAME in InferenceService"
                  exit 1
                fi
                _kv_events_args=(--kv-events-config "{ \
                  \"enable_kv_cache_events\": true, \
                  \"publisher\": \"zmq\", \
                  \"endpoint\": \"tcp://${_inference_pool_name}:5557\", \
                  \"topic\": \"kv@${POD_IP}:8000@${ISVC_MODEL_NAME}\" \
                }")
              fi

              VLLM_NIXL_SIDE_CHANNEL_PORT=30020 \
              exec vllm serve \
                "${ISVC_MODEL_PATH}" \
                --served-model-name "${ISVC_MODEL_NAME}" \
                --port 8000 \
                --tensor-parallel-size {{ "{{" }} or .Spec.Parallelism.Tensor 1 {{ "}}" }} \
                {{ "{{" }} if .Spec.Parallelism.Expert {{ "}}" }}--enable-expert-parallel{{ "{{" }} end {{ "}}" }} \
                ${_config_arg} \
                "${_kv_events_args[@]}" \
                $(ISVC_EXTRA_ARGS)
          env:
            - name: ISVC_PRESET_PATH
              value: ""
            - name: ISVC_PRE_PROCESS_SCRIPT
              value: ""
            - name: ISVC_USE_KV_EVENTS
              value: "false"
            - name: ISVC_MODEL_NAME
              value: "meta-llama/Llama-3.2-1B-Instruct"
            - name: ISVC_MODEL_PATH
              value: "$(ISVC_MODEL_NAME)"
            - name: ISVC_EXTRA_ARGS
              value: >-
                --disable-uvicorn-access-log
                --no-enable-log-requests
            - name: UCX_TLS
              value: rocm_copy,rocm_ipc,self,sm,rc_x
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
