{{- if .Values.ecrTokenRefresher.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mif.ecrTokenRefresher.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.ecrTokenRefresher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mif.ecrTokenRefresher.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mif.ecrTokenRefresher.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mif.ecrTokenRefresher.fullname" . }}-init
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.ecrTokenRefresher.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mif.ecrTokenRefresher.fullname" . }}-init
subjects:
  - kind: ServiceAccount
    {{- if .Values.ecrTokenRefresher.serviceAccount.create }}
    name: {{ include "mif.ecrTokenRefresher.serviceAccountName" . }}-init
    {{- else }}
    name: {{ include "mif.ecrTokenRefresher.serviceAccountName" . }}
    {{- end }}
    namespace: {{ include "common.names.namespace" . }}
{{- end }}
