{{- if .Values.ecrTokenRefresher.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mif.ecrTokenRefresher.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.ecrTokenRefresher.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.ecrTokenRefresher.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ecrTokenRefresher.aws.secretAccessKey | b64enc }}
{{- end }}
