{{- if .Values.ecrTokenRefresher.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mif.ecrTokenRefresher.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.ecrTokenRefresher.labels" . | nindent 4 }}
  {{- with .Values.ecrTokenRefresher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ecrTokenRefresher.serviceAccount.automount }}
{{- end }}
