{{- if .Values.ecrTokenRefresher.enabled }}
{{- if .Values.ecrTokenRefresher.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mif.ecrTokenRefresher.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.ecrTokenRefresher.labels" . | nindent 4 }}
  {{- with .Values.ecrTokenRefresher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ecrTokenRefresher.serviceAccount.automount }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mif.ecrTokenRefresher.serviceAccountName" . }}-init
  namespace: {{ include "common.names.namespace" . }}
  labels:
    {{- include "mif.ecrTokenRefresher.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- with .Values.ecrTokenRefresher.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.ecrTokenRefresher.serviceAccount.automount }}
{{- end }}
{{- end }}
