apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: vllm-dp-decode-meta
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  workerTemplate:
    metadata:
      labels:
        heimdall.moreh.io/role: decode
