apiVersion: odin.moreh.io/v1alpha1
kind: InferenceServiceTemplate
metadata:
  name: vllm-dp-hf-hub-offline
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  workerTemplate:
    spec:
      containers:
        - name: main
          env:
            - name: HF_HOME
              value: /mnt/model
            - name: HF_HUB_OFFLINE
              value: "1"
          volumeMounts:
            - name: model
              mountPath: /mnt/model
      volumes:
        - name: model
          persistentVolumeClaim:
            claimName: model
