apiVersion: v2
name: moai-inference-framework
description: Moreh Inference Framework
type: application
version: 0.0.0
appVersion: "0.0.0"
home: https://github.com/moreh-dev/mif
sources:
  - https://github.com/moreh-dev/mif/tree/main/deploy/helm/moai-inference-framework
dependencies:
  - name: common
    version: 2.31.4
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: kube-prometheus-stack
    alias: prometheus-stack
    version: 80.7.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-stack.enabled
  - name: lws
    version: 0.7.0
    repository: oci://registry.k8s.io/lws/charts
    condition: lws.enabled
  - name: odin
    version: v0.3.0
    repository: https://moreh-dev.github.io/helm-charts
    condition: odin.enabled
  - name: odin-crd
    version: v0.3.0
    repository: https://moreh-dev.github.io/helm-charts
    condition: odin-crd.enabled
  - name: kubernetes-replicator
    alias: replicator
    version: 2.12.2
    repository: https://helm.mittwald.de
    condition: replicator.enabled
