apiVersion: v2
name: moai-inference-preset
description: Moreh Inference Framework Preset
type: application
version: 0.0.0
appVersion: "0.0.0"
home: https://docs.moreh.io/
sources:
  - https://github.com/moreh-dev/mif/tree/main/deploy/helm/moai-inference-preset
dependencies:
  - name: common
    version: 2.31.4
    repository: oci://registry-1.docker.io/bitnamicharts
